name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1
    - name: Installation
      run: |
          sudo apt install libc6-dev-i386 build-essential
          sudo apt install nasm qemu bochs
    - name: Make
      run: make
